#!/usr/bin/env bash
# install-hooks.sh — one-time bootstrap for git hooks in standards/
#
# Usage:  bash install-hooks.sh
#
# NOTE: When used within Z-ai-governance, hooks are managed by the
# parent's .husky/ configuration. This script is for standalone use only.
#
# What it does:
#   1. Creates .husky/pre-commit if it does not exist
#   2. Runs verify-standards.js on commit (content-level invariants V04-V10)
#   3. Cross-repo ID-graph checks (G01-G15) run in CI and in the
#      parent repo pre-commit hook.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if [ ! -d .git ]; then
  echo "[install-hooks] Not a git repository: $REPO_ROOT"
  echo "[install-hooks] Run 'git init' first, then re-run this script."
  exit 1
fi

# Check if already managed by parent platform
if [ -d .husky ] && [ -f .husky/pre-commit ]; then
  echo "[install-hooks] .husky/pre-commit already exists (likely managed by parent repo)."
  echo "[install-hooks] Skipping standalone hook setup."
  exit 0
fi

echo "[install-hooks] Creating .husky/pre-commit for standalone use"
mkdir -p .husky
cat > .husky/pre-commit << 'HOOK'
#!/usr/bin/env bash
# Auto-generated by standards/install-hooks.sh (standalone mode)
set -euo pipefail

if command -v node >/dev/null 2>&1; then
  echo "[standards pre-commit] Running verify-standards.js..."
  if ! node standards/scripts/verify-standards.js 2>&1; then
    echo "[standards pre-commit] FAIL: verify-standards.js reported violations."
    exit 1
  fi
  echo "[standards pre-commit] OK: verify-standards.js PASS"
else
  echo "[standards pre-commit] WARNING: Node.js not found — skipping verify."
fi
HOOK
chmod +x .husky/pre-commit

echo "[install-hooks] Done. Hook installed: .husky/pre-commit"
echo ""
echo "[install-hooks] To bypass a hook for ONE commit (not recommended):"
echo "  git commit --no-verify"